name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ARM32
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: ./2.4
      run: docker build . --file Dockerfile --tag webdavarm:$(date +%s)
